### ISSUE TITLE
Cascade identifier on Nuget

### ISSUE THREAD

**Issue by mrpmorris** [jbuechner/cascade#1]
Hi Jens

I've written Blazor University and Fluxor. More recently I've written Reducible and a library named Cascade to complement Fluxor.

I should have checked Nuget first :)

You currently own the Cascade ID on Nuget for a package that hasn't been updated in about 10 years. I'm writing to ask if you'd be willing to relinquish the name to me so I can use it?

Many thanks.

Pete

**Comment by jbuechner** [comment]
Hi,

sorry for my late response. I added you as an owner. As nuget does not support permanent removal of an existing published package you are stuck with it and its existing versions. I am completely ok if you want to go and contact the nuget support to remove it entirely, so you can republish it without the existing versions. There is not a single project I am aware of that is using it, so that their primary concern of breaking the dependency chain shouldn't be a problem here.
